@OrderService_HostAddress = http://localhost:5002

GET {{OrderService_HostAddress}}/weatherforecast/
Accept: application/json

### Get all orders
GET {{OrderService_HostAddress}}/orders
Accept: application/json

### Get all orders. Version 3
GET {{OrderService_HostAddress}}/v1/orders
Accept: application/json


### Get a specific order by ID
GET {{OrderService_HostAddress}}/orders/1
Accept: application/json

### Create a new order
POST {{OrderService_HostAddress}}/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6InNvbWUtdXNlci1pZCIsImV4cCI6MTc1NTI1OTY4OH0.pE7WYhvdduRdOianXMU592hSUpBDmTwRdyqhz34izZA

{
  "productName": "Laptop",
  "quantity": 2,
  "price": 1500.00,
  "orderDate": "2024-08-12T00:00:00Z"
}

### Create a new order. Validation error
POST {{OrderService_HostAddress}}/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6InNvbWUtdXNlci1pZCIsImV4cCI6MTc1NTI1OTY4OH0.pE7WYhvdduRdOianXMU592hSUpBDmTwRdyqhz34izZA

{
  "productName": "2",
  "quantity": -2,
  "price": 1500.99
}

### Update an existing order by ID
PUT {{OrderService_HostAddress}}/orders/1
Content-Type: application/json

{
  "productName": "Gaming Laptop",
  "quantity": 1,
  "price": 2000.00,
  "orderDate": "2024-08-12T00:00:00Z"
}

### Delete an order by ID
DELETE {{OrderService_HostAddress}}/orders/1

### Health Check - Liveness
GET {{OrderService_HostAddress}}/health/live

### Health Check - Readiness
GET {{OrderService_HostAddress}}/health/ready

### Auth get token
POST {{OrderService_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}